// app/(private)/dashboard/implementing-agencies/constants/agency-table.constants.ts

import { AgencyColumnConfig, AgencySortOptionConfig } from "../types/agency-table.types";

export const TABLE_IDENTIFIER = "implementing-agencies-table";

export const DEFAULT_ROW_HEIGHT = 42;
export const MIN_ROW_HEIGHT = 28;

export const DEFAULT_COLUMNS: AgencyColumnConfig[] = [
  {
    key: "code",
    label: "Code",
    width: 100,
    flex: 1,
    minWidth: 70,
    maxWidth: 180,
    type: "text",
    align: "left",
    defaultVisible: true,
  },
  {
    key: "fullName",
    label: "Agency Name",
    width: 250,
    flex: 2.5,
    minWidth: 180,
    maxWidth: 500,
    type: "text",
    align: "left",
    defaultVisible: true,
  },
  {
    key: "type",
    label: "Type",
    width: 120,
    flex: 1,
    minWidth: 90,
    maxWidth: 180,
    type: "badge",
    align: "center",
    defaultVisible: false,
  },
  {
    key: "category",
    label: "Category",
    width: 140,
    flex: 1.2,
    minWidth: 100,
    maxWidth: 220,
    type: "text",
    align: "left",
    defaultVisible: false,
  },
  {
    key: "contactPerson",
    label: "Contact Person",
    width: 160,
    flex: 1.5,
    minWidth: 120,
    maxWidth: 280,
    type: "text",
    align: "left",
    defaultVisible: false,
  },
  {
    key: "contactEmail",
    label: "Email",
    width: 180,
    flex: 1.5,
    minWidth: 120,
    maxWidth: 300,
    type: "text",
    align: "left",
    defaultVisible: false,
  },
  {
    key: "contactPhone",
    label: "Phone",
    width: 130,
    flex: 1,
    minWidth: 100,
    maxWidth: 200,
    type: "text",
    align: "left",
    defaultVisible: false,
  },
  {
    key: "address",
    label: "Address",
    width: 200,
    flex: 2,
    minWidth: 140,
    maxWidth: 400,
    type: "text",
    align: "left",
    defaultVisible: false,
  },
  {
    key: "totalProjects",
    label: "Projects",
    width: 100,
    flex: 0.8,
    minWidth: 70,
    maxWidth: 150,
    type: "number",
    align: "right",
    defaultVisible: true,
  },
  {
    key: "totalBreakdowns",
    label: "Breakdowns",
    width: 110,
    flex: 0.8,
    minWidth: 80,
    maxWidth: 160,
    type: "number",
    align: "right",
    defaultVisible: true,
  },
  {
    key: "isActive",
    label: "Status",
    width: 100,
    flex: 0.8,
    minWidth: 80,
    maxWidth: 150,
    type: "status",
    align: "center",
    defaultVisible: false,
  },
  {
    key: "createdAt",
    label: "Created",
    width: 120,
    flex: 1,
    minWidth: 100,
    maxWidth: 180,
    type: "date",
    align: "left",
    defaultVisible: false,
  },
  {
    key: "updatedAt",
    label: "Last Modified",
    width: 120,
    flex: 1,
    minWidth: 100,
    maxWidth: 180,
    type: "date",
    align: "left",
    defaultVisible: false,
  },
];

export const DEFAULT_HIDDEN_COLUMNS = new Set(
  DEFAULT_COLUMNS.filter(c => !c.defaultVisible).map(c => String(c.key))
);

export const AGENCY_SORT_OPTIONS: AgencySortOptionConfig[] = [
  { value: "lastModified", label: "Default: Last Modified" },
  { value: "lastModifiedAsc", label: "Last Modified: Oldest First" },
  { value: "nameAsc", label: "Agency Name: A-Z" },
  { value: "nameDesc", label: "Agency Name: Z-A" },
  { value: "codeAsc", label: "Code: A-Z" },
  { value: "codeDesc", label: "Code: Z-A" },
  { value: "projectsDesc", label: "Projects: Most to Least" },
  { value: "projectsAsc", label: "Projects: Least to Most" },
  { value: "typeAsc", label: "Type: Internal First" },
  { value: "typeDesc", label: "Type: External First" },
];
